# Site
title:          MT Resources
bio:            'A collection of Music Therapy resources and information'
description:    "A collection of Music Therapy resources for professionals and students"
picture:        'assets/img/photo3 copy.png'
locale:         en_US
#url:            


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
email: megancrandallmtbc@gmail.com
twitter: MusicUnifies
facebook: postacutemedical
#google:
  #plus: #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#github: username
#stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: megan-crandall-mtbc
#xing: username
instagram: MusicUnifies
#lastfm: username
#tumblr: username
pinterest: meganvcrandall
#foursquare: username
#steam: username
#dribbble: username
youtube: 
soundcloud: mvdolan
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# Comments
#disqus_shortname: alperenbozkurt-net


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
